<?php

namespace GlpiPlugin\Gdmsintegration\Service;

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;

final class HistoryExportService
{
    public static function export(Request $request): BinaryFileResponse
    {

        \Session::checkRight('config', READ);

        $entities_id = (int) ($request->query->get('entities_id', \Session::getActiveEntity()));
        if (!\Session::haveAccessToEntity($entities_id)) {
            throw new \Glpi\Exception\Http\AccessDeniedHttpException();
        }

        // Respect chart_days config
        $cfg_obj   = new \GlpiPlugin\Gdmsintegration\Config();
        $cfg       = $cfg_obj->getConfigByEntity($entities_id);
        $chart_days = max(7, min(365, (int)($cfg['chart_days'] ?? 60)));

        // ── Build data ──────────────────────────────────────────────────────────────
        $state_obj   = new \GlpiPlugin\Gdmsintegration\Device();
        $all_states  = $state_obj->find();
        $history_obj = new \GlpiPlugin\Gdmsintegration\History();
        $history_ago = gmdate('Y-m-d H:i:s', strtotime("-{$chart_days} days"));
        $hist_rows   = $history_obj->find(['date' => ['>', $history_ago]], ['date ASC']);

        // MAC → device name (GLPI first, then cloud_name stored by sync, then MAC)
        $mac_to_name = [];
        // Index cloud names from device state
        foreach ($all_states as $state) {
            $m = strtolower(trim($state['mac'] ?? ''));
            if ($m && !empty($state['cloud_name'])) {
                $mac_to_name[$m] = $state['cloud_name'];
            }
        }
        // GLPI asset names override cloud_name
        foreach (['NetworkEquipment', 'Phone'] as $itemtype) {
            $obj = new $itemtype();
            foreach ($obj->find() as $row) {
                $m = strtolower(trim($row['uuid'] ?? ''));
                if ($m && !empty($row['name'])) $mac_to_name[$m] = $row['name'];
            }
        }
        // Final fallback: use MAC address itself
        foreach ($all_states as $st) {
            $m = strtolower(trim($st['mac'] ?? ''));
            if ($m && empty($mac_to_name[$m])) $mac_to_name[$m] = strtoupper($st['mac']);
        }

        // Build per_device[mac][day] = [online, total]
        $per_device = [];
        $all_days   = [];
        foreach ($hist_rows as $h) {
            $day    = substr($h['date'] ?? '', 0, 10);
            $mac    = strtolower(trim($h['mac'] ?? ''));
            $status = $h['status'] ?? '';
            if (!$day || !$mac) continue;
            $all_days[$day] = true;
            if (!isset($per_device[$mac][$day])) $per_device[$mac][$day] = ['online' => 0, 'total' => 0];
            $per_device[$mac][$day]['total']++;
            if ($status === 'online') $per_device[$mac][$day]['online']++;
        }
        ksort($all_days);
        $days = array_keys($all_days);
        $devices = array_keys($per_device);

        // ── Spreadsheet ─────────────────────────────────────────────────────────────
        $spreadsheet = new Spreadsheet();
        $spreadsheet->getProperties()
            ->setCreator('GDMS Integration — GLPI')
            ->setTitle(__('Device Availability', 'gdmsintegration'))
            ->setDescription(sprintf(__('Last %d days — generated by GDMS Integration plugin', 'gdmsintegration'), $chart_days));

        // ─── Sheet 1: Summary (pivot — rows=days, cols=devices) ─────────────────────
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle(mb_substr(sprintf(__('%% Online %d days', 'gdmsintegration'), $chart_days), 0, 31));

        // Header row
        $sheet->setCellValue('A1', __('Date', 'gdmsintegration'));
        foreach ($devices as $ci => $mac) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
            $sheet->setCellValue($col . '1', $mac_to_name[$mac] ?? $mac);
        }

        // Style header row
        $lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex(count($devices) + 1);
        $sheet->getStyle("A1:{$lastCol}1")->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1A56DB']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
        ]);

        // Data rows
        foreach ($days as $ri => $day) {
            $row = $ri + 2;
            $sheet->setCellValue("A{$row}", $day);
            $sheet->getStyle("A{$row}")->getNumberFormat()->setFormatCode('YYYY-MM-DD');

            foreach ($devices as $ci => $mac) {
                $col   = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
                $d     = $per_device[$mac][$day] ?? ['online' => 0, 'total' => 0];
                $pct   = $d['total'] > 0 ? round($d['online'] / $d['total'] * 100, 1) : null;
                if ($pct !== null) {
                    $cell = $col . $row;
                    $sheet->setCellValue($cell, $pct / 100);
                    $sheet->getStyle($cell)->getNumberFormat()
                        ->setFormatCode(NumberFormat::FORMAT_PERCENTAGE_00);
                    // Color gradient: green ≥90, yellow ≥50, red <50
                    $rgb = $pct >= 90 ? 'D4EDDA' : ($pct >= 50 ? 'FFF3CD' : 'F8D7DA');
                    $sheet->getStyle($cell)->getFill()
                        ->setFillType(Fill::FILL_SOLID)
                        ->getStartColor()->setRGB($rgb);
                }
            }
        }

        // Column widths
        $sheet->getColumnDimension('A')->setWidth(14);
        foreach ($devices as $ci => $mac) {
            $col   = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
            $width = max(mb_strlen($mac_to_name[$mac] ?? $mac) + 2, 14);
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        // Freeze header row
        $sheet->freezePane('A2');

        // Auto-filter
        $sheet->setAutoFilter("A1:{$lastCol}1");

        // ─── Sheet 2: Device summary ────────────────────────────────────────────────
        $sum = $spreadsheet->createSheet();
        $sum->setTitle(mb_substr(__('Summary', 'gdmsintegration'), 0, 31));
        $sum->setCellValue('A1', __('Device', 'gdmsintegration'));
        $sum->setCellValue('B1', 'MAC');
        $sum->setCellValue('C1', __('Availability %', 'gdmsintegration'));
        $sum->setCellValue('D1', __('Days online', 'gdmsintegration'));
        $sum->setCellValue('E1', __('Total days', 'gdmsintegration'));
        $sum->setCellValue('F1', 'SLA');

        $sum->getStyle('A1:F1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1A56DB']],
        ]);

        $sr = 2;
        foreach ($devices as $mac) {
            $totalDays = 0; $onlineDays = 0;
            foreach ($days as $day) {
                $d = $per_device[$mac][$day] ?? null;
                if (!$d) continue;
                $totalDays++;
                if ($d['total'] > 0 && $d['online'] / $d['total'] >= 0.5) $onlineDays++;
            }
            $avail = $totalDays > 0 ? $onlineDays / $totalDays : 0;
            $sla   = $avail >= 0.999 ? __('Gold', 'gdmsintegration') : ($avail >= 0.99 ? __('Silver', 'gdmsintegration') : ($avail >= 0.95 ? __('Bronze', 'gdmsintegration') : __('Critical', 'gdmsintegration')));

            $sum->setCellValue("A{$sr}", $mac_to_name[$mac] ?? $mac);
            $sum->setCellValue("B{$sr}", strtoupper($mac));
            $sum->setCellValue("C{$sr}", $avail);
            $sum->getStyle("C{$sr}")->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_PERCENTAGE_00);
            $sum->setCellValue("D{$sr}", $onlineDays);
            $sum->setCellValue("E{$sr}", $totalDays);
            $sum->setCellValue("F{$sr}", $sla);

            $rgb = $avail >= 0.95 ? 'D4EDDA' : ($avail >= 0.90 ? 'FFF3CD' : 'F8D7DA');
            $sum->getStyle("C{$sr}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB($rgb);
            $sr++;
        }

        foreach (['A' => 26, 'B' => 22, 'C' => 16, 'D' => 12, 'E' => 12, 'F' => 10] as $col => $w) {
            $sum->getColumnDimension($col)->setWidth($w);
        }

        // ─── Sheet 3: GDMS tickets for the same chart_days reporting window ─────────
        self::addTicketsSheet($spreadsheet, $entities_id, $chart_days);

        // ─── Output ──────────────────────────────────────────────────────────────────
        $spreadsheet->setActiveSheetIndex(0);

        $filename = 'gdms_history_' . date('Y-m-d') . '.xlsx';

        $tmpFile = tempnam(sys_get_temp_dir(), 'gdms_history_');
        if ($tmpFile === false) {
            throw new \RuntimeException('Unable to create temporary export file.');
        }
        $writer = new Xlsx($spreadsheet);
        $writer->save($tmpFile);

        $response = new \Symfony\Component\HttpFoundation\BinaryFileResponse($tmpFile);
        $response->headers->set('Content-Type', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        $response->setContentDisposition(
            \Symfony\Component\HttpFoundation\ResponseHeaderBag::DISPOSITION_ATTACHMENT,
            $filename
        );
        $response->headers->set('Cache-Control', 'no-cache, no-store');
        $response->deleteFileAfterSend(true);
        return $response;
    }

    /**
     * Add a flat export of GDMS-generated GLPI tickets for the same
     * chart_days reporting window used by the availability history.
     *
     * The sheet exposes objective GLPI/GDMS data only. It does not evaluate
     * KPI, SLA or compliance status.
     */
    private static function addTicketsSheet(Spreadsheet $spreadsheet, int $entities_id, int $chart_days): void {
        global $DB;

        $sheet = $spreadsheet->createSheet();
        $sheet->setTitle('Tickets');

        $from = gmdate('Y-m-d H:i:s', strtotime("-{$chart_days} days"));

        $ticket_rows = [];
        try {
            $ticket_rows = $DB->request([
                'SELECT' => [
                    'id', 'name', 'content', 'date', 'date_mod', 'status', 'type',
                    'urgency', 'impact', 'priority', 'entities_id',
                    'itilcategories_id', 'requesttypes_id', 'users_id_recipient',
                    'solvedate', 'closedate',
                ],
                'FROM'   => \Ticket::getTable(),
                'WHERE'  => [
                    'entities_id' => $entities_id,
                    'date'        => ['>=', $from],
                    'name'        => ['LIKE', '[GDMS]%'],
                ],
                'ORDER'  => ['date DESC', 'id DESC'],
            ]);
        } catch (\Throwable $e) {
            \GlpiPlugin\Gdmsintegration\Utils::debug('XLSX ticket export query failed: ' . $e->getMessage());
            return;
        }

        $tickets = [];
        $ticket_ids = [];
        $user_ids = [];
        $category_ids = [];
        $requesttype_ids = [];

        foreach ($ticket_rows as $row) {
            $id = (int)($row['id'] ?? 0);
            if ($id <= 0) {
                continue;
            }
            $tickets[$id] = $row;
            $ticket_ids[] = $id;
            $v = (int)($row['users_id_recipient'] ?? 0);
            if ($v > 0) $user_ids[$v] = true;
            $v = (int)($row['itilcategories_id'] ?? 0);
            if ($v > 0) $category_ids[$v] = true;
            $v = (int)($row['requesttypes_id'] ?? 0);
            if ($v > 0) $requesttype_ids[$v] = true;
        }

        $users = self::loadNamedRows(\User::getTable(), $user_ids);
        $categories = self::loadNamedRows(\ITILCategory::getTable(), $category_ids);
        $request_types = self::loadNamedRows(\RequestType::getTable(), $requesttype_ids);

        $assignments = [];
        if ($ticket_ids) {
            try {
                $rows = $DB->request([
                    'SELECT' => ['tickets_id', 'users_id'],
                    'FROM'   => \Ticket_User::getTable(),
                    'WHERE'  => [
                        'tickets_id' => $ticket_ids,
                        'type'      => \Ticket_User::ASSIGN,
                    ],
                ]);
                foreach ($rows as $row) {
                    $tid = (int)($row['tickets_id'] ?? 0);
                    $uid = (int)($row['users_id'] ?? 0);
                    if ($tid > 0 && $uid > 0) {
                        $assignments[$tid][] = $uid;
                    }
                }
            } catch (\Throwable $e) {
                \GlpiPlugin\Gdmsintegration\Utils::debug('XLSX ticket assignment query failed: ' . $e->getMessage());
            }
        }
        $assignment_user_ids = [];
        foreach ($assignments as $uids) foreach ($uids as $uid) $assignment_user_ids[$uid] = true;
        $assigned_users = self::loadNamedRows(\User::getTable(), $assignment_user_ids);

        $relations = [];
        $item_ids_by_type = ['NetworkEquipment' => [], 'Phone' => []];
        if ($ticket_ids) {
            try {
                $rows = $DB->request([
                    'SELECT' => ['tickets_id', 'itemtype', 'items_id'],
                    'FROM'   => \Item_Ticket::getTable(),
                    'WHERE'  => ['tickets_id' => $ticket_ids],
                    'ORDER'  => ['id ASC'],
                ]);
                foreach ($rows as $row) {
                    $tid = (int)($row['tickets_id'] ?? 0);
                    $type = (string)($row['itemtype'] ?? '');
                    $item_id = (int)($row['items_id'] ?? 0);
                    if ($tid <= 0 || $item_id <= 0 || !isset($item_ids_by_type[$type])) continue;
                    if (!isset($relations[$tid])) $relations[$tid] = [];
                    $relations[$tid][] = [$type, $item_id];
                    $item_ids_by_type[$type][$item_id] = true;
                }
            } catch (\Throwable $e) {
                \GlpiPlugin\Gdmsintegration\Utils::debug('XLSX ticket item relation query failed: ' . $e->getMessage());
            }
        }

        $assets = [];
        foreach ($item_ids_by_type as $itemtype => $ids_map) {
            if (!$ids_map) continue;
            try {
                $obj = new $itemtype();
                foreach ($obj->find(['id' => array_keys($ids_map)]) as $asset) {
                    $id = (int)($asset['id'] ?? 0);
                    if ($id <= 0) continue;
                    $assets[$itemtype . ':' . $id] = [
                        'name' => (string)($asset['name'] ?? ''),
                        'serial' => (string)($asset['serial'] ?? ''),
                        'uuid' => (string)($asset['uuid'] ?? ''),
                    ];
                }
            } catch (\Throwable $e) {
                \GlpiPlugin\Gdmsintegration\Utils::debug('XLSX ticket asset lookup failed for ' . $itemtype . ': ' . $e->getMessage());
            }
        }

        $headers = [
            __('Ticket ID', 'gdmsintegration'),
            __('Created', 'gdmsintegration'),
            __('Updated', 'gdmsintegration'),
            __('Status', 'gdmsintegration'),
            __('Title', 'gdmsintegration'),
            __('Description', 'gdmsintegration'),
            __('Type', 'gdmsintegration'),
            __('Urgency', 'gdmsintegration'),
            __('Impact', 'gdmsintegration'),
            __('Priority', 'gdmsintegration'),
            __('Category', 'gdmsintegration'),
            __('Request source', 'gdmsintegration'),
            __('Requester', 'gdmsintegration'),
            __('Assigned technician', 'gdmsintegration'),
            __('Asset type', 'gdmsintegration'),
            __('Asset', 'gdmsintegration'),
            __('MAC / UUID', 'gdmsintegration'),
            __('Serial', 'gdmsintegration'),
            __('Event', 'gdmsintegration'),
            __('Solved', 'gdmsintegration'),
            __('Closed', 'gdmsintegration'),
            __('Elapsed', 'gdmsintegration'),
        ];
        $sheet->fromArray($headers, null, 'A1');
        $sheet->getStyle('A1:V1')->applyFromArray([
            'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
            'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1A56DB']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);

        $row_num = 2;
        foreach ($tickets as $row) {
            $tid = (int)$row['id'];
            $created = (string)($row['date'] ?? '');
            $updated = (string)($row['date_mod'] ?? '');
            $solved = (string)($row['solvedate'] ?? '');
            $closed = (string)($row['closedate'] ?? '');
            $event = self::detectTicketEvent((string)($row['name'] ?? ''));

            $asset_type = '';
            $asset_name = '';
            $asset_uuid = '';
            $asset_serial = '';
            foreach ($relations[$tid] ?? [] as [$it, $iid]) {
                $key = $it . ':' . $iid;
                if (!isset($assets[$key])) continue;
                if ($asset_name !== '') continue;
                $asset_type = $it;
                $asset_name = $assets[$key]['name'];
                $asset_uuid = $assets[$key]['uuid'];
                $asset_serial = $assets[$key]['serial'];
            }

            $requester_id = (int)($row['users_id_recipient'] ?? 0);
            $requester = $requester_id > 0 ? ($users[$requester_id] ?? '') : '';
            $tech_names = [];
            foreach ($assignments[$tid] ?? [] as $uid) {
                if (!empty($assigned_users[$uid])) $tech_names[] = $assigned_users[$uid];
            }

            $elapsed_seconds = '';
            $end = $closed !== '' ? $closed : ($solved !== '' ? $solved : '');
            if ($end !== '' && $created !== '') {
                $start_ts = strtotime($created);
                $end_ts = strtotime($end);
                if ($start_ts !== false && $end_ts !== false && $end_ts >= $start_ts) {
                    $elapsed_seconds = $end_ts - $start_ts;
                }
            }

            $url = \Ticket::getFormURLWithID($tid);

            $values = [
                $tid,
                $created,
                $updated,
                self::ticketStatusLabel((int)($row['status'] ?? 0)),
                (string)($row['name'] ?? ''),
                (string)($row['content'] ?? ''),
                self::ticketTypeLabel((int)($row['type'] ?? 0)),
                (int)($row['urgency'] ?? 0),
                (int)($row['impact'] ?? 0),
                (int)($row['priority'] ?? 0),
                $categories[(int)($row['itilcategories_id'] ?? 0)] ?? '',
                $request_types[(int)($row['requesttypes_id'] ?? 0)] ?? '',
                $requester,
                implode(', ', $tech_names),
                $asset_type,
                $asset_name,
                $asset_uuid !== '' ? strtoupper($asset_uuid) : '',
                $asset_serial !== '' ? strtoupper($asset_serial) : '',
                $event,
                $solved,
                $closed,
                $elapsed_seconds,
            ];
            $sheet->fromArray($values, null, 'A' . $row_num);

            $sheet->getCell('A' . $row_num)->getHyperlink()->setUrl($url);
            $sheet->getStyle('A' . $row_num)->getFont()->setUnderline(Font::UNDERLINE_SINGLE);

            foreach (['B', 'C', 'T', 'U'] as $col) {
                if ($sheet->getCell($col . $row_num)->getValue() !== '') {
                    $sheet->getStyle($col . $row_num)->getNumberFormat()->setFormatCode('yyyy-mm-dd hh:mm');
                }
            }
            if ($elapsed_seconds !== '') {
                $sheet->getCell('V' . $row_num)->setValue($elapsed_seconds / 86400);
                $sheet->getStyle('V' . $row_num)->getNumberFormat()->setFormatCode('[hh]:mm:ss');
            }
            $row_num++;
        }

        $last_row = max(1, $row_num - 1);
        $sheet->setAutoFilter('A1:V' . $last_row);
        $sheet->freezePane('A2');
        $widths = [10, 20, 20, 16, 42, 50, 14, 10, 10, 10, 28, 22, 24, 28, 20, 30, 24, 20, 22, 20, 20, 16];
        foreach ($widths as $i => $width) {
            $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($i + 1);
            $sheet->getColumnDimension($col)->setWidth($width);
        }
        $sheet->getStyle('E2:F' . $last_row)->getAlignment()->setWrapText(true);
        $sheet->getStyle('A1:V' . $last_row)->getAlignment()->setVertical(Alignment::VERTICAL_TOP);
    }

    /** @param array<int,bool> $ids @return array<int,string> */
    private static function loadNamedRows(string $table, array $ids): array {
        global $DB;
        if (!$ids) return [];
        $result = [];
        try {
            foreach ($DB->request([
                'SELECT' => ['id', 'name'],
                'FROM'   => $table,
                'WHERE'  => ['id' => array_keys($ids)],
            ]) as $row) {
                $id = (int)($row['id'] ?? 0);
                if ($id > 0) $result[$id] = (string)($row['name'] ?? '');
            }
        } catch (\Throwable $e) {
            \GlpiPlugin\Gdmsintegration\Utils::debug('XLSX named-row lookup failed for ' . $table . ': ' . $e->getMessage());
        }
        return $result;
    }

    private static function detectTicketEvent(string $title): string {
        if (str_contains($title, '[GWN-ALERT:')) return __('GWN Alert', 'gdmsintegration');
        if (str_contains($title, '[GDMS-WAN-NOINET:')) return __('WAN - No Internet', 'gdmsintegration');
        if (str_contains($title, '[GDMS-WAN:')) return __('WAN - Link Down', 'gdmsintegration');
        return __('Device Offline', 'gdmsintegration');
    }

    private static function ticketStatusLabel(int $status): string {
        return match ($status) {
            \Ticket::INCOMING => __('New', 'gdmsintegration'),
            \Ticket::ASSIGNED => __('Assigned', 'gdmsintegration'),
            \Ticket::PLANNED => __('Planned', 'gdmsintegration'),
            \Ticket::WAITING => __('Pending', 'gdmsintegration'),
            \Ticket::SOLVED => __('Solved', 'gdmsintegration'),
            \Ticket::CLOSED => __('Closed', 'gdmsintegration'),
            default => (string)$status,
        };
    }

    private static function ticketTypeLabel(int $type): string {
        return match ($type) {
            \Ticket::INCIDENT_TYPE => __('Incident', 'gdmsintegration'),
            \Ticket::DEMAND_TYPE   => __('Request', 'gdmsintegration'),
            default                 => (string) $type,
        };
    }

}
