<?php
// Import is handled by config.form.php — this standalone endpoint is disabled.
http_response_code(404);
exit;
/**
 * GDMS Integration — History import from availability Excel export
 *
 * Reads gdms_history_*.xlsx (generated by history_export.php).
 * Sheet 1: pivot  — col A = date, remaining cols = daily % per device (0.0–1.0 decimal)
 * Sheet 2: summary — col A = device name, col B = MAC
 *
 * For each device-day cell, inserts 100 synthetic records spaced 14.4 min apart
 * so the dashboard's online/total ratio matches the original percentage (±1% accuracy).
 * Days that already have any record for that MAC are skipped entirely.
 */

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Shared\Date as XlDate;
use PhpOffice\PhpSpreadsheet\Cell\Coordinate;

// PhpSpreadsheet 2.x removed getCellByColumnAndRow — use this helper instead
function gdms_cell(\PhpOffice\PhpSpreadsheet\Worksheet\Worksheet $sheet, int $col, int $row): \PhpOffice\PhpSpreadsheet\Cell\Cell {
    return $sheet->getCell(Coordinate::stringFromColumnIndex($col) . $row);
}

Session::checkRight('config', UPDATE);

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    Html::back();
}

$upload = $_FILES['history_xlsx'] ?? null;
if (!$upload || $upload['error'] !== UPLOAD_ERR_OK || empty($upload['tmp_name'])) {
    Session::addMessageAfterRedirect(
        __('No file received or upload error.', 'gdmsintegration'), false, ERROR
    );
    Html::back();
}

try {
    $spreadsheet = IOFactory::load($upload['tmp_name']);
} catch (\Exception $e) {
    Session::addMessageAfterRedirect(
        __('Could not read file:', 'gdmsintegration') . ' ' . $e->getMessage(), false, ERROR
    );
    Html::back();
}

if ($spreadsheet->getSheetCount() < 2) {
    Session::addMessageAfterRedirect(
        __('File must contain at least 2 sheets (pivot + summary).', 'gdmsintegration'), false, ERROR
    );
    Html::back();
}

// ── Sheet 2 (index 1): name → MAC mapping ───────────────────────────────────
$sumSheet  = $spreadsheet->getSheet(1);
$sumRows   = $sumSheet->getHighestRow();
$nameToMac = [];

for ($r = 2; $r <= $sumRows; $r++) {
    $name = trim((string) gdms_cell($sumSheet, 1, $r)->getValue());
    $mac  = strtolower(trim((string) gdms_cell($sumSheet, 2, $r)->getValue()));
    if ($name !== '' && $mac !== '') {
        $nameToMac[strtolower($name)] = $mac;
    }
}

// ── Sheet 1 (index 0): pivot data ───────────────────────────────────────────
$pivotSheet = $spreadsheet->getSheet(0);
$maxCol     = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::columnIndexFromString(
                  $pivotSheet->getHighestColumn());
$maxRow     = $pivotSheet->getHighestRow();

// Map column index → MAC from header row
$colToMac = [];
for ($c = 2; $c <= $maxCol; $c++) {
    $header = trim((string) gdms_cell($pivotSheet, $c, 1)->getValue());
    if ($header === '') continue;

    $mac = $nameToMac[strtolower($header)] ?? null;
    if ($mac === null) {
        // Header may be the MAC itself
        $clean = strtolower(preg_replace('/[^0-9a-fA-F:]/', '', $header));
        if (strlen($clean) >= 12) $mac = $clean;
    }
    if ($mac !== null) $colToMac[$c] = $mac;
}

if (empty($colToMac)) {
    Session::addMessageAfterRedirect(
        __('No recognizable device columns found. Ensure the file was exported by this plugin.', 'gdmsintegration'),
        false, WARNING
    );
    Html::back();
}

// ── Pre-load existing day-coverage per MAC ──────────────────────────────────
$histObj  = new PluginGdmsintegrationHistory();
$existing = []; // mac_lower → [day => true]
foreach ($histObj->find() as $h) {
    $m = strtolower(trim($h['mac'] ?? ''));
    $d = substr($h['date'] ?? '', 0, 10);
    if ($m !== '' && $d !== '') $existing[$m][$d] = true;
}

// ── Build synthetic records and batch-insert ─────────────────────────────────
// Each device-day becomes exactly 100 records spaced 864s apart (≈14.4 min,
// same order of magnitude as the 10-min cron). First $online_n records are
// 'online', the rest 'offline' — gives online/total = pct to ±1%.
global $DB;

// 100 records per device-day → ±1% accuracy on online/total ratio
$RECORDS_PER_DAY = 100;
$STEP_SECONDS    = 864; // 86400s / 100

$inserted_days = 0;
$skipped_days  = 0;

for ($r = 2; $r <= $maxRow; $r++) {
    $rawDay = gdms_cell($pivotSheet, 1, $r)->getValue();
    if ($rawDay === null || $rawDay === '') continue;

    if (is_numeric($rawDay)) {
        $day = XlDate::excelToDateTimeObject((float)$rawDay)->format('Y-m-d');
    } else {
        $day = substr(trim((string)$rawDay), 0, 10);
    }
    if (!preg_match('/^\d{4}-\d{2}-\d{2}$/', $day)) continue;

    foreach ($colToMac as $c => $mac) {
        if (!empty($existing[$mac][$day])) { $skipped_days++; continue; }

        $val = gdms_cell($pivotSheet, $c, $r)->getValue();
        if ($val === null || $val === '') continue; // no data — skip

        $pct      = max(0.0, min(1.0, (float)$val));
        $online_n = (int) round($pct * $RECORDS_PER_DAY);
        $base_ts  = strtotime($day . ' 00:08:00');
        // strtotime returns false on parse failure → false+n=0 → epoch timestamp
        // MySQL TIMESTAMP rejects values ≤ 1970-01-01 00:00:00 (warning 1299)
        if ($base_ts === false || $base_ts < 86400) { $skipped_days++; continue; }

        for ($i = 0; $i < $RECORDS_PER_DAY; $i++) {
            $DB->insert('glpi_plugin_gdmsintegration_history', [
                'mac'    => $mac,
                'status' => $i < $online_n ? 'online' : 'offline',
                'date'   => date('Y-m-d H:i:s', $base_ts + $i * $STEP_SECONDS),
            ]);
        }

        $existing[$mac][$day] = true;
        $inserted_days++;
    }
}

Session::addMessageAfterRedirect(
    sprintf(
        __('Import complete: %d device-days imported (%d records each), %d device-days skipped (already had data).', 'gdmsintegration'),
        $inserted_days, $RECORDS_PER_DAY, $skipped_days
    ),
    true, INFO
);
Html::back();
