<?php
/**
 * GDMS Integration — History export to Excel
 * Uses PHPOffice\PhpSpreadsheet bundled in GLPI vendor/.
 */

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Style\NumberFormat;

Session::checkRight('config', READ);

$entities_id = (int) ($_GET['entities_id'] ?? $_SESSION['glpiactive_entity'] ?? 0);
if (!Session::haveAccessToEntity($entities_id)) {
    Html::displayRightError();
}

// Respect chart_days config
$cfg_obj   = new PluginGdmsintegrationConfig();
$cfg       = $cfg_obj->getConfigByEntity($entities_id);
$chart_days = max(7, min(365, (int)($cfg['chart_days'] ?? 60)));

// ── Build data ──────────────────────────────────────────────────────────────
$state_obj   = new PluginGdmsintegrationDevice();
$all_states  = $state_obj->find();
$history_obj = new PluginGdmsintegrationHistory();
$history_ago = gmdate('Y-m-d H:i:s', strtotime("-{$chart_days} days"));
$hist_rows   = $history_obj->find(['date' => ['>', $history_ago]], ['date ASC']);

// MAC → device name (GLPI first, then cloud_name stored by sync, then MAC)
$mac_to_name = [];
// Index cloud names from device state
foreach ($all_states as $state) {
    $m = strtolower(trim($state['mac'] ?? ''));
    if ($m && !empty($state['cloud_name'])) {
        $mac_to_name[$m] = $state['cloud_name'];
    }
}
// GLPI asset names override cloud_name
foreach (['NetworkEquipment', 'Phone'] as $itemtype) {
    $obj = new $itemtype();
    foreach ($obj->find() as $row) {
        $m = strtolower(trim($row['uuid'] ?? ''));
        if ($m && !empty($row['name'])) $mac_to_name[$m] = $row['name'];
    }
}
// Final fallback: use MAC address itself
foreach ($all_states as $st) {
    $m = strtolower(trim($st['mac'] ?? ''));
    if ($m && empty($mac_to_name[$m])) $mac_to_name[$m] = strtoupper($st['mac']);
}

// Build per_device[mac][day] = [online, total]
$per_device = [];
$all_days   = [];
foreach ($hist_rows as $h) {
    $day    = substr($h['date'] ?? '', 0, 10);
    $mac    = strtolower(trim($h['mac'] ?? ''));
    $status = $h['status'] ?? '';
    if (!$day || !$mac) continue;
    $all_days[$day] = true;
    if (!isset($per_device[$mac][$day])) $per_device[$mac][$day] = ['online' => 0, 'total' => 0];
    $per_device[$mac][$day]['total']++;
    if ($status === 'online') $per_device[$mac][$day]['online']++;
}
ksort($all_days);
$days = array_keys($all_days);
$devices = array_keys($per_device);

// ── Spreadsheet ─────────────────────────────────────────────────────────────
$spreadsheet = new Spreadsheet();
$spreadsheet->getProperties()
    ->setCreator('GDMS Integration — GLPI')
    ->setTitle(__('Device Availability', 'gdmsintegration'))
    ->setDescription(sprintf(__('Last %d days — generated by GDMS Integration plugin', 'gdmsintegration'), $chart_days));

// ─── Sheet 1: Summary (pivot — rows=days, cols=devices) ─────────────────────
$sheet = $spreadsheet->getActiveSheet();
$sheet->setTitle(mb_substr(sprintf(__('%% Online %d days', 'gdmsintegration'), $chart_days), 0, 31));

// Header row
$sheet->setCellValue('A1', __('Date', 'gdmsintegration'));
foreach ($devices as $ci => $mac) {
    $col = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
    $sheet->setCellValue($col . '1', $mac_to_name[$mac] ?? $mac);
}

// Style header row
$lastCol = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex(count($devices) + 1);
$sheet->getStyle("A1:{$lastCol}1")->applyFromArray([
    'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1A56DB']],
    'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER],
]);

// Data rows
foreach ($days as $ri => $day) {
    $row = $ri + 2;
    $sheet->setCellValue("A{$row}", $day);
    $sheet->getStyle("A{$row}")->getNumberFormat()->setFormatCode('YYYY-MM-DD');

    foreach ($devices as $ci => $mac) {
        $col   = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
        $d     = $per_device[$mac][$day] ?? ['online' => 0, 'total' => 0];
        $pct   = $d['total'] > 0 ? round($d['online'] / $d['total'] * 100, 1) : null;
        if ($pct !== null) {
            $cell = $col . $row;
            $sheet->setCellValue($cell, $pct / 100);
            $sheet->getStyle($cell)->getNumberFormat()
                ->setFormatCode(NumberFormat::FORMAT_PERCENTAGE_00);
            // Color gradient: green ≥90, yellow ≥50, red <50
            $rgb = $pct >= 90 ? 'D4EDDA' : ($pct >= 50 ? 'FFF3CD' : 'F8D7DA');
            $sheet->getStyle($cell)->getFill()
                ->setFillType(Fill::FILL_SOLID)
                ->getStartColor()->setRGB($rgb);
        }
    }
}

// Column widths
$sheet->getColumnDimension('A')->setWidth(14);
foreach ($devices as $ci => $mac) {
    $col   = \PhpOffice\PhpSpreadsheet\Cell\Coordinate::stringFromColumnIndex($ci + 2);
    $width = max(mb_strlen($mac_to_name[$mac] ?? $mac) + 2, 14);
    $sheet->getColumnDimension($col)->setWidth($width);
}

// Freeze header row
$sheet->freezePane('A2');

// Auto-filter
$sheet->setAutoFilter("A1:{$lastCol}1");

// ─── Sheet 2: Device summary ────────────────────────────────────────────────
$sum = $spreadsheet->createSheet();
$sum->setTitle(mb_substr(__('Summary', 'gdmsintegration'), 0, 31));
$sum->setCellValue('A1', __('Device', 'gdmsintegration'));
$sum->setCellValue('B1', 'MAC');
$sum->setCellValue('C1', __('Availability %', 'gdmsintegration'));
$sum->setCellValue('D1', __('Days online', 'gdmsintegration'));
$sum->setCellValue('E1', __('Total days', 'gdmsintegration'));
$sum->setCellValue('F1', 'SLA');

$sum->getStyle('A1:F1')->applyFromArray([
    'font' => ['bold' => true, 'color' => ['rgb' => 'FFFFFF']],
    'fill' => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['rgb' => '1A56DB']],
]);

$sr = 2;
foreach ($devices as $mac) {
    $totalDays = 0; $onlineDays = 0;
    foreach ($days as $day) {
        $d = $per_device[$mac][$day] ?? null;
        if (!$d) continue;
        $totalDays++;
        if ($d['total'] > 0 && $d['online'] / $d['total'] >= 0.5) $onlineDays++;
    }
    $avail = $totalDays > 0 ? $onlineDays / $totalDays : 0;
    $sla   = $avail >= 0.999 ? __('Gold', 'gdmsintegration') : ($avail >= 0.99 ? __('Silver', 'gdmsintegration') : ($avail >= 0.95 ? __('Bronze', 'gdmsintegration') : __('Critical', 'gdmsintegration')));

    $sum->setCellValue("A{$sr}", $mac_to_name[$mac] ?? $mac);
    $sum->setCellValue("B{$sr}", strtoupper($mac));
    $sum->setCellValue("C{$sr}", $avail);
    $sum->getStyle("C{$sr}")->getNumberFormat()->setFormatCode(NumberFormat::FORMAT_PERCENTAGE_00);
    $sum->setCellValue("D{$sr}", $onlineDays);
    $sum->setCellValue("E{$sr}", $totalDays);
    $sum->setCellValue("F{$sr}", $sla);

    $rgb = $avail >= 0.95 ? 'D4EDDA' : ($avail >= 0.90 ? 'FFF3CD' : 'F8D7DA');
    $sum->getStyle("C{$sr}")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setRGB($rgb);
    $sr++;
}

foreach (['A' => 26, 'B' => 22, 'C' => 16, 'D' => 12, 'E' => 12, 'F' => 10] as $col => $w) {
    $sum->getColumnDimension($col)->setWidth($w);
}

// ─── Output ──────────────────────────────────────────────────────────────────
$spreadsheet->setActiveSheetIndex(0);

$filename = 'gdms_disponibilidad_' . date('Y-m-d') . '.xlsx';

header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
header('Content-Disposition: attachment; filename="' . $filename . '"');
header('Cache-Control: max-age=0');
header('Pragma: public');

$writer = new Xlsx($spreadsheet);
$writer->save('php://output');
exit;
